apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "copilot-api-app1"

  links:
    - url: https://github.com/ItRachii/aws-elasticbeanstalk-20231128053937
      title: "copilot-api-app1"
      icon: code

  labels:
    system: web-apps
    trackid: "aws-elasticbeanstalk-20231128053937"
    environmentname: copilot-api-env1

  tags:
    - java
    - aws
    - "applicationtype-webapplication"

  annotations:
    # add elastic beanstalk annotation
    jenkins.io/github-folder: 'custom-actions/tf-copilot-api-app1'
    github.com/project-slug: ItRachii/aws-elasticbeanstalk-20231128053937
    backstage.io/techdocs-ref: dir:.
    backstage.io/linguist: https://github.com/ItRachii/spring-boot-ebs
    sonarqube.org/project-key: 'demo-app/aws-elb-java'

spec:
  type: service
  lifecycle: experimental
  system: elasticbeanstalk
  owner: "group:default/ey"
